---
-
    hosts: all
    roles:
        - terminal
        - gui
    tasks:
        -
            name: install remaining apt dependencies
            apt:
                name: "{{ item }}"
                state: present
            with_items:
                - curl
                - silversearcher-ag
        -
            name: install remaining python deps
            pip:
                name: "{{ item }}"
            with_items:
                - ansible-lint
                - yamllint
            become: true
