---
-
  hosts: all
  roles: # i believe these roles cannot use include role as they add keywords to ansible itself
    - suzuki-shunsuke.pyenv # gets pyenv
    - suzuki-shunsuke.pyenv-module # allows use of pyenv in playbooks
    - suzuki-shunsuke.pyenv-virtualenv # allows use of virtual env in playbooks
    - terminal
    - gui
      #  tasks:
    #    -  debug: var=ansible_facts
    #       become: yes
    #        -
        #            name: install remaining python deps
        #    pip:
        #        name: "{{ item }}"
        #    with_items:
        #        - ansible-lint
        #        - yamllint
