---
- hosts: all
  tasks:
    - 
      name: install dependencies for vim
      apt: 
        name=libncurses5-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=libgnome2-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=libgnomeui-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=libgtk2.0-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=libatk1.0-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=libbonoboui2-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=libcairo2-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=libx11-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=libxpm-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=libxt-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=python-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=python3-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=ruby-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=lua5.1
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=liblua5.1-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=libperl-dev
        state=present
      become: true
    - 
      name: install dependencies for vim
      apt: 
        name=git
        state=present
      become: true
    -
      name: grab vim source
      git:
        repo: 'https://github.com/vim/vim.git'
        depth: 1
        dest: /home/vagrant/vim
    -
      name: configure vim
      #NOTE: trying both python's here. this may interfere with
      #youcomplete me. To  fix, just turn python3 off.
      #https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source
      shell: ./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=yes \
            --enable-pythoninterp=yes \
            --with-python-config-dir=/usr/lib/python2.7/config \
            --enable-python3interp=yes \
            --with-python3-config-dir=/usr/lib/python3.4/config \
            --enable-perlinterp=yes \
            --enable-luainterp=yes \
            --enable-gui=gtk2 \
            --enable-cscope \
            --prefix=/usr/local
      args:
        chdir: /home/vagrant/vim
    -
      name: build vim
      shell: make
      args:
        chdir: /home/vagrant/vim
    -
      name: install vim
      shell: make install
      args:
        chdir: /home/vagrant/vim
      become: true
    -
      name: set up vim edit defaults
      shell: update-alternatives --install /usr/bin/editor editor /usr/local/bin/vim 1
      become: true
    -
      name: set up vim edit defaults
      shell: update-alternatives --set editor /usr/local/bin/vim
      become: true
    -
      name: set up vim edit defaults
      shell: update-alternatives --install /usr/local/bin/vi vi /usr/local/bin/vim 1
      become: true
    -
      name: set up vim edit defaults
      shell: update-alternatives --set vi /usr/local/bin/vim
      become: true
    - 
      name: install silver searcher
      apt:
        name=silversearcher-ag
        state=present
      become: true
    -
      name: install git
      apt:
        name: git
        state: present
      become: true
    -
      name: install curl
      apt: 
        name=curl=7.35.0-1ubuntu2.10
        state=present
      become: true
    -
       name: install YADM without messing with the apt repositories
       get_url:
         url: https://github.com/TheLocehiliosan/yadm/raw/master/yadm
         dest: /usr/local/bin/yadm
         mode: a+x
       become: true
    -
       name: install zsh
       apt:
         name=zsh
       become: true
    - 
       name: set zsh as default shell to vagrant
       user:
         name: vagrant
         shell: /bin/zsh
       become: true
    -
       name: install oh-my-zsh
       git:
         repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
         depth: 1
         dest: /home/vagrant/.oh-my-zsh
    -
      name: figure out whether yadm is already installed
      stat: path=/home/vagrant/.yadm/repo.git
      register: yadm_exists
    -
      name: YADM clone my repo
      shell: yadm clone https://www.github.com/austinwiltshire/yadm.git
      when: yadm_exists.stat.exists == False
#Get vim just right
    -
      name: Grab vundle for vim
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: /home/vagrant/.vim/bundle/Vundle.vim
    -
      name: Pull in all vim plugins
      shell: vim +PluginInstall +qall
    - 
      name: Install youcomplete me with clang completion
      shell:  python2.7 ./install.py --clang-completer
      args:
         chdir: ~/.vim/bundle/YouCompleteMe
    -
      name: make undo directory for vim
      file:
         path: /home/vagrant/.vim/undo
         state: directory
    - 
      name: make backup directory for vim
      file:
         path: /home/vagrant/.vim/backup
         state: directory
    - 
      name: make swap directory for vim
      file:
         path: /home/vagrant/.vim/swap
         state: directory
#For docker
    -
#be nice to get a single version for this
      name: Grab apt transport https, needed for docker
      apt: 
        name=apt-transport-https
      become: true
    -
#be nice to get a single version for this
      name: Grab ca-certificats, needed for docker
      apt: 
        name=ca-certificates
      become: true
    -
      name: get apt-keys for docker apt stuff
      apt_key:
        keyserver: hkp://ha.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
      become: true
    -
#this has to line up with the version of ubuntu we're on - 14.04 is trusty
      name: install repo for docker
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
        state: present
      become: true
    -
#in the below, the 3.13.0-92-generic was the result of running uname -r on
#the image. This could be automated
      name: gather linux extra dependencies
      apt:
        name=linux-image-extra-3.13.0-92-generic
      become: true
    -
      name: gather linux extra virtual dependencies
      apt:
        name=linux-image-extra-virtual
      become: true
    -
#be nice to get a version locked down here.
      name: install docker itself!
      apt:
        name=docker-engine
      become: true
    -
      name: start the docker service
      service:
        name: docker
        enabled: yes
        state: started
#docker compose
    -
       name: install docker compose
       get_url:
         url: "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64"
         dest: /usr/local/bin/docker-compose
         mode: a+x
       become: true
#tmux
    -
       name: install tmux
       apt:
         name=tmux=1.8-5
       become: true
    -
       name: install xfce4
       apt:
         name=xfce4
       become: true
    -
       name: install xfce4 extras
       apt:
         name=xfce4-goodies
       become: true
    -
       name: install xfce4 icons 1
       apt:
         name=gnome-icon-theme
       become: true
    -
       name: install xfce4 icons 2
       apt:
         name=tango-icon-theme
       become: true
    -
       name: clone universal ctags
       git:
         repo: 'https://github.com/universal-ctags/ctags.git'
         depth: 1
         dest: /tmp/ctags
    -
       name: install autoreconf, needed for ctags
       apt:
         name=autoconf
       become: true
    -
       name: install pkg-config, needed for ctags
       apt:
         name=pkg-config
       become: true
    -
       name: prep building universal ctags
       shell: ./autogen.sh
       args:
         chdir: /tmp/ctags
         creates: /tmp/ctags/configure
    -
       name: configure universal ctags
       shell: ./configure
       args:
         chdir: /tmp/ctags
         creates: /tmp/ctags/Makefile
    -
       name: install universal ctags
       shell: make install
       args:
         chdir: /tmp/ctags
         creates: /usr/local/bin/ctags
       become: true
    -
    #NOTE: you may also have to install these on your host machine if
    #using vagrant. For a windows host, that means going through each
    #folder in windows explorer, selecting the fonts and right clicking
    #to install
    #you can also search it in the search bar to the right to select
    #all otf and ttf files, and install that way.
       name: clone powerline fonts
       git:
         repo: 'https://github.com/powerline/fonts.git'
         depth: 1
         dest: /tmp/powerline-fonts
    -
       name: install fonts
       shell: ./install.sh
       args:
         chdir: /tmp/powerline-fonts
    - 
       name: install pre-reqs for lpass cli openssl
       apt: name=openssl state=present
       become: true
    - 
       name: install pre-reqs for lpass cli libcurl4
       apt: name=libcurl4-openssl-dev state=present
       become: true
    - 
       name: install pre-reqs for lpass cli libxml2
       apt: name=libxml2 state=present
       become: true
    - 
       name: install pre-reqs for lpass cli libssl-dev
       apt: name=libssl-dev state=present
       become: true
    - 
       name: install pre-reqs for lpass cli libxml2-dev
       apt: name=libxml2-dev state=present
       become: true
    - 
       name: install pre-reqs for lpass cli pinentry
       apt: name=pinentry-curses state=present
       become: true
    - 
       name: install pre-reqs for lpass cli xclip
       apt: name=xclip state=present
       become: true
    - 
       name: install pre-reqs for lpass cli cmake
       apt: name=cmake state=present
       become: true
    - 
       name: install pre-reqs for lpass cli build-essential
       apt: name=build-essential state=present
       become: true
    - 
       name: install pre-reqs for lpass cli pkg-config
       apt: name=pkg-config state=present
       become: true
    - 
       name: install pre-reqs for lpass cli asciidoc
       apt: name=asciidoc state=present
       become: true
    - 
       name: install pre-reqs for lpass cli xsltproc
       apt: name=xsltproc state=present
       become: true
    -
       name: clone lastpass itself
       git:
         repo: 'https://github.com/lastpass/lastpass-cli'
         depth: 1
         dest: /tmp/lastpass-cli
    -
       name: build lastpass
       shell: make
       args:
         chdir: /tmp/lastpass-cli
    -
       name: install lastpass
       shell: make install
       args:
         chdir: /tmp/lastpass-cli
       become: true
    -
       name: install lastpass docs
       shell: make install-doc
       args:
         chdir: /tmp/lastpass-cli
       become: true
    -
       name: grab miniconda
       shell: wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
       args:
         creates: ~/miniconda.sh
       become: true
       become_user: vagrant
    -
       name: install miniconda
       shell: bash ~/miniconda.sh -b -p ~/miniconda
       args:
         creates: ~/miniconda/bin
       become: true
       become_user: vagrant

    -
       name: install ipython
       shell: ~/miniconda/bin/conda install ipython #full path because ansible doesn't run .zshrc
       args:
         creates: ~/miniconda/bin/ipython
       become: true
       become_user: vagrant
    -
       name: install git-flow
       apt: name=git-flow state=present
       become: true
