---
-
  hosts: all
  roles:
    - gui
    - suzuki-shunsuke.pyenv # gets pyenv
    - suzuki-shunsuke.pyenv-module # allows use of pyenv in playbooks
    - suzuki-shunsuke.pyenv-virtualenv # allows use of virtual env in playbooks
    - terminal
  tasks:
    -  name: install remaining apt dependencies
       apt:
         name: "{{ item }}"
         state: present
       with_items:
         - curl
         - silversearcher-ag
       become: yes
    #        -
        #            name: install remaining python deps
        #    pip:
        #        name: "{{ item }}"
        #    with_items:
        #        - ansible-lint
        #        - yamllint
