---
-
    hosts: all
    roles:
        - terminal
        - gui
    tasks:
        -
            name: install curl
            apt:
                name: curl
                state: present
            become: true
        -
            name: install silver searcher
            apt:
                name: silversearcher-ag
                state: present
            become: true
        -
            name: install ansible-lint
            command: /usr/bin/pip install ansible-lint
            args:
                creates: /usr/local/bin/ansible-lint
            become: true
        -
            name: install yamllint
            command: /usr/bin/pip install yamllint
            args:
                creates: /usr/local/bin/yamllint
            become: true
