--- #surprisingly complicated
    -
       name: clone universal ctags
       git:
         repo: 'https://github.com/universal-ctags/ctags.git'
         depth: 1
         dest: /tmp/ctags
         version: master
    -
       name: install autoreconf, needed for ctags
       apt:
         name=autoconf
       become: true
    -
       name: install pkg-config, needed for ctags
       apt:
         name=pkg-config
       become: true
    -
       name: prep building universal ctags
       command: ./autogen.sh
       args:
         chdir: /tmp/ctags
         creates: /tmp/ctags/configure
    -
       name: configure universal ctags
       command: ./configure
       args:
         chdir: /tmp/ctags
         creates: /tmp/ctags/Makefile
    -
       name: install universal ctags
       command: make install
       args:
         chdir: /tmp/ctags
         creates: /usr/local/bin/ctags
       become: true

