---
#be nice to get a single version for this
    -
      name: Grab apt transport https, needed for docker
      apt:
        name=apt-transport-https
      become: true
    -
#be nice to get a single version for this
      name: Grab ca-certificats, needed for docker
      apt:
        name=ca-certificates
      become: true
    -
      name: get apt-keys for docker apt stuff
      apt_key:
        keyserver: hkp://ha.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
      become: true
    -
#this has to line up with the version of ubuntu we're on - 14.04 is trusty
      name: install repo for docker
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
        state: present
      become: true
    -
#in the below, the 3.13.0-92-generic was the result of running uname -r on
#the image. This could be automated
      name: gather linux extra dependencies
      apt:
        name=linux-image-extra-3.13.0-92-generic
      become: true
    -
      name: gather linux extra virtual dependencies
      apt:
        name=linux-image-extra-virtual
      become: true
    -
#be nice to get a version locked down here.
      name: install docker itself!
      apt:
        name=docker-engine
      become: true
    -
      name: start the docker service
      service:
        name: docker
        enabled: yes
        state: started
#docker compose
    -
       name: install docker compose
       get_url:
         url: "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64"
         dest: /usr/local/bin/docker-compose
         mode: a+x
       become: true
