---
    -
       name: install zsh
       apt:
         name=zsh
       become: true
    -
       name: set zsh as default shell to vagrant
       user:
         name: vagrant
         shell: /bin/zsh
       become: true
    -
       name: install oh-my-zsh
       git:
         repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
         depth: 1
         dest: /home/vagrant/.oh-my-zsh
         version: master
