---
-
    name: install repo ubuntu-make
    apt_repository:
        repo: ppa:ubuntu-desktop/ubuntu-make
        state: present
    become: true
-
    name: install ubuntu-make
    apt:
        name: ubuntu-make
        state: present
    become: true
-
    name: install IDEs (pycharm, clion)
    command: "umake ide {{ item.name }} {{ item.path }}"
    with_items:
        - {name: "pycharm-professional",
           path: "~/.local/share/umake/ide/pycharm-professional"}
        - {name: "clion",
           path: "~/.local/share/umake/ide/clion"}
    args:
        creates: "{{ item.path }}"
    become_user: vagrant
    become: true
