---
-
    name: install ubuntu-make
    apt:
        name: ubuntu-make
        state: present
    become: yes
-
    name: install IDEs (pycharm, clion)
    command: "umake ide {{ item.name }} {{ item.path }}"
    with_items:
        - {name: "pycharm-professional",
           path: "/home/austinwiltshire/.local/share/umake/ide/pycharm-professional"}
        - {name: "clion",
           path: "/home/austinwiltshire/.local/share/umake/ide/clion"}
    args:
        creates: "{{ item.path }}"
    become: yes # this hsouldn't require become, but umake doesn't like to run without it. weird.
    #we have to use the fully qualified path above because we're sudo when we run this.
