---
-   
    name: add latest ubuntu-make repo. Needed for ubuntu 16.04, shouldn't hurt others.
    apt_repository:
        repo: "ppa:ubuntu-desktop/ubuntu-make"
        state: present
    become: yes
-
    name: install ubuntu-make
    apt:
        name: ubuntu-make
        state: present
    become: yes
-
    name: install IDEs (pycharm, clion)
    command: "umake ide {{ item.name }} {{ item.path }}"
    with_items:
        - {name: "pycharm-professional",
           path: "{{ ansible_facts['user_dir'] }}/.local/share/umake/ide/pycharm-professional"}
        - {name: "clion",
           path: "{{ ansible_facts['user_dir'] }}/.local/share/umake/ide/clion"}
    args:
        creates: "{{ item.path }}"
    register: task_ides_var
    until: task_ides_var is not failed
    retries: 5
-
    name: install plantuml # used for pycharm's plantuml plugin
    apt:
        name: plantuml
        state: present
    become: yes
