---
-
    name: install ubuntu-make
    apt:
        name: ubuntu-make
        state: present
    become: yes
-
    name: install IDEs (pycharm, clion)
    command: "umake ide {{ item.name }} {{ item.path }}"
    with_items:
        - {name: "pycharm-professional",
           path: "{{ ansible_facts['user_dir'] }}/.local/share/umake/ide/pycharm-professional"}
        - {name: "clion",
           path: "{{ ansible_facts['user_dir'] }}/.local/share/umake/ide/clion"}
    args:
        creates: "{{ item.path }}"
    register: task_ides_var
    until: task_ides_var is not failed
    retries: 5
