---
-
    name: add gcc repo
    apt_repository:
        repo: ppa:ubuntu-toolchain-r/test
        state: present
    become: true
-
    name: install GCC/G++ 6
    apt:
        name: "{{ item }}"
        state: present
    become: true
    with_items:
        - gcc-6
        - g++-6
        - ccache
        - cppcheck
-
    name: update alternatives for gcc
    alternatives:
        link: "{{ item.link }}"
        name: "{{ item.name }}"
        path: "{{ item.path }}"
    become: true
    with_items:
        - {link: "/usr/bin/gcc", name: "gcc", path: "/usr/bin/gcc-6"}
        - {link: "/usr/bin/g++", name: "g++", path: "/usr/bin/g++-6"}
