---
-
    name: install GCC/G++
    apt:
        name: "{{ item }}"
        state: present
    become: true
    with_items:
        - gcc
        - g++
        - ccache
        - cppcheck
        - cmake
