---
-
    name: clone universal ctags
    git:
        repo: 'https://github.com/universal-ctags/ctags.git'
        depth: 1
        dest: ~/.local/tmp/ctags
        version: master
-
    name: install CTAGS dependencies
    apt:
        name: "{{ item }}"
        state: present
    with_items:
        - autoconf
        - pkg-config
    become: yes
-
#TODO: get the current home directory programmatically, don't use ausitnwiltshire
    name: build and install universal ctags
    command: "{{ item }}"
    with_items:
        - ./autogen.sh
        - ./configure --prefix=/home/austinwiltshire/.local
        - make install
    args:
        chdir: ~/.local/tmp/ctags
        creates: /home/austinwiltshire/.local/bin/ctags
