---
-
    name: clone universal ctags
    git:
        repo: 'https://github.com/universal-ctags/ctags.git'
        depth: 1
        dest: "{{ ansible_facts['user_dir'] }}/.local/tmp/ctags"
        version: master
-
    name: install CTAGS dependencies
    apt:
        name: "{{ item }}"
        state: present
    with_items:
        - autoconf
        - pkg-config
    become: yes
-
    name: build and install universal ctags
    command: "{{ item }}"
    with_items:
        - ./autogen.sh
        - "./configure --prefix={{ ansible_facts['user_dir'] }}/.local"
        - make install
    args:
        chdir: ~/.local/tmp/ctags
        creates: "{{ ansible_facts['user_dir'] }}/.local/bin/ctags"
