---
-
    name: clone universal ctags
    git:
        repo: 'https://github.com/universal-ctags/ctags.git'
        depth: 1
        dest: /tmp/ctags
        version: master
-
    name: install CTAGS dependencies
    apt:
        name: "{{ item }}"
        state: present
    with_items:
        - autoconf
        - pkg-config
    become: true
-
    name: build and install universal ctags
    command: "{{ item }}"
    with_items:
        - ./autogen.sh
        - ./configure
        - make install
    args:
        chdir: /tmp/ctags
        creates: /usr/local/bin/ctags
    become: true
