---
-
    name: Install docker
    apt:
        name: docker.io
        state: present
    become: yes
-
    name: start docker
    service:
        name: docker
        state: started
    become: yes
-
    name: enable docker
    service:
        name: docker
        enabled: yes
    become: yes
