---
-
    name: Install apt-transport-https
    apt:
        name: apt-transport-https
        state: present
    become: yes
-
    name: Install certificates
    apt:
        name: ca-certificates
        state: present
    become: yes
-
    name: Install docker-ce
    apt:
        name: docker-ce
        state: present
    become: yes
-
    name: Install docker-ce cli
    apt:
        name: docker-ce-cli
        state: present
    become: yes
-
    name: Install container.io
    apt:
        name: containerd.io
        state: present
    become: yes
-
    name: start docker
    service:
        name: docker
        state: started
    become: yes
-
    name: enable docker
    service:
        name: docker
        enabled: yes
    become: yes
