---
-
    name: clone fzf
    git:
        repo: 'https://github.com/junegunn/fzf.git'
        depth: 1
        dest: "{{ ansible_facts['user_dir'] }}/.fzf"
-
    name: install fzf
    command: "{{ ansible_facts['user_dir'] }}/.fzf/install"
