---
-
    name: install git
    apt:
        name: git
        state: present
-
    name: install git-flow
    apt:
        name: git-flow
        state: present
-
    name: config git
    command: "git config --global {{ item }}"
    with_items:
        - "user.name \"John Graham\""
        - "user.email john.a.graham@gmail.com"
        - "push.default simple"
    become_user: "vagrant"
