---
-
    name: install pre-reqs for lastpass cli
    apt:
        name: "{{ item }}"
        state: present
    with_items:
        - openssl
        - libcurl4-openssl-dev
        - libxml2
        - libxml2-dev
        - libssl-dev
        - pinentry-curses
        - xclip
        - build-essential
        - pkg-config
        - xsltproc
        - cmake3
          # - asciidoc # not needed, installs a gig of dependencies for docs
    become: true
-
    name: clone lastpass itself
    git:
        repo: 'https://github.com/lastpass/lastpass-cli'
        depth: 1
        dest: /tmp/lastpass-cli
        version: master
-
    name: build and install lastpass
    command: "{{ item }}"
    args:
        chdir: /tmp/lastpass-cli
        creates: /usr/bin/lpass
    with_items:
        - make
        - make install
        # - make install-doc # to install a gig of documentation
-
    name: build lastpass
    command: make
    args:
        chdir: /tmp/lastpass-cli
        creates: /tmp/lastpass-cli/build/lpass
-
    name: install lastpass
    command: make install
    args:
        chdir: /tmp/lastpass-cli
        creates: /usr/bin/lpass
    become: true
