---
-
    name: install pre-reqs for lastpass cli
    apt:
        name: "{{ item }}"
        state: present
    with_items:
        - openssl
        - libcurl4-openssl-dev
        - libxml2
        - libxml2-dev
        - libssl-dev
        - pinentry-curses
        - xclip
        - build-essential
        - pkg-config
        - xsltproc
        - cmake
          # - asciidoc # not needed, installs a gig of dependencies for docs
    become: yes
-
    name: clone lastpass itself
    git:
        repo: 'https://github.com/lastpass/lastpass-cli'
        depth: 1
        dest: ~/.local/tmp/lastpass-cli
        version: master
    become_user: "austinwiltshire"
-
    name: build and install lastpass
    command: "{{ item }}"
    args:
        chdir: ~/.local/tmp/lastpass-cli
        creates: ~/.local/bin/lpass
    with_items:
        - PREFIX="/home/austinwiltshire/.local" make
        - PREFIX="/home/austinwiltshire/.local" make install
        # - make install-doc # to install a gig of documentation
    become_user: "austinwiltshire"
