---
-
    name: install pre-reqs for lastpass cli
    apt:
        name: ["openssl", "libcurl4-openssl-dev", "libxml2", "libxml2-dev", "libssl-dev", "pinentry-curses", "xclip", "build-essential", "pkg-config", "xsltproc", "cmake"]
        state: present
          # - asciidoc # not needed, installs a gig of dependencies for docs
    become: yes
-
    name: clone lastpass itself
    git:
        repo: 'https://github.com/lastpass/lastpass-cli'
        depth: 1
        dest: "{{ ansible_facts['user_dir'] }}/.local/tmp/lastpass-cli"
        version: master
-
    name: build and install lastpass
    command: "{{ item }}"
    environment:
      PREFIX: "{{ ansible_facts['user_dir'] }}/.local/tmp/lastpass-cli"
    args:
        chdir: "{{ ansible_facts['user_dir'] }}/.local/tmp/lastpass-cli"
        creates: "{{ ansible_facts['user_dir'] }}/.local/bin/lpass"
    with_items:
        - make
        - make install PREFIX=~/.local
        # - make install-doc # to install a gig of documentation
