---
- include_tasks: "{{ task_item }}"
  with_items:
      - git.yml
      - zsh.yml
      - python.yml
      - tmux.yml
      - vim.yml
      - yadm.yml
      - vim_plugins.yml
      - docker.yml
      - ctags.yml
      - powerline.yml
      - lastpass-cli.yml
      - cpp.yml
  loop_control:
      loop_var: task_item
