---
- include_tasks: "{{ task_item }}"
  with_items:
         - cpp.yml
         - python.yml
         - git.yml
         - zsh.yml
         - tmux.yml
         - yadm.yml
         - vim.yml
         - vim_plugins.yml
         - docker.yml
         - ctags.yml
         - powerline.yml
         - lastpass-cli.yml
  loop_control:
      loop_var: task_item
