---
-
    name: pyenv install 2.7.16
    pyenv:
      version: 2.7.16
      pyenv_root: "~/.pyenv"
-
    name: install virtualenv
    pip:
      name: virtualenv
      executable: "{{pyenv_root}}/versions/2.7.16/bin/pip"
