---
-   
    name: install Python Requirements
    apt:
        name: ["make", "build-essential", "libssl-dev", "zlib1g-dev", "libbz2-dev", "libreadline6-dev", "libsqlite3-dev", "wget", "curl", "llvm", "libncurses5-dev", "libncursesw5-dev", "xz-utils", "tk-dev", "python3-dev", "libffi-dev"]
        state: present
    become: true
    # list updated from: https://github.com/suzuki-shunsuke/ansible-pyenv/blob/master/defaults/main.yml
-
    name: pyenv install 2.7.16
    pyenv:
      version: 2.7.16
      pyenv_root: "{{ ansible_facts['user_dir'] }}/.pyenv"
    environment:
      PYTHON_CONFIGURE_OPTS: "--enable-shared" # various libs need the shared object to work, like theano
-
    name: pyenv install 3.7.3 
    pyenv:
      version: 3.7.3
      pyenv_root: "{{ ansible_facts['user_dir'] }}/.pyenv"
    environment:
      PYTHON_CONFIGURE_OPTS: "--enable-shared" # you complete me needs python 3, and needs it shared
