---
-
    name: set up vim defaults
    alternatives:
        name: "{{ item.name }}"
        path: "{{ item.path }}"
    with_items:
      #TODO: how do we find out where vim is? is there a way to detect vim and then plug it into the path variable?
        - {name: "editor", path: "/usr/bin/vim"}
        - {name: "vi", path: "/usr/bin/vim"}
    become: yes
