---
#-
#    name: install VIM dependencies to build vim ourselves
#    apt:
#        name: "{{ item }}"
#        state: present
#    with_items:
#        - libncurses5-dev
#        - libgnome2-dev
#        - libgnomeui-dev
#        - libgtk2.0-dev
#        - libatk1.0-dev
#        - libbonoboui2-dev
#        - libcairo2-dev
#        - libx11-dev
#        - libxpm-dev
#        - libxt-dev
#        - python-dev
#        - python3-dev
#        - ruby-dev
#        - lua5.1
#        - liblua5.1-dev
#        - libperl-dev
#        - git
#-
#    name: grab vim source
#    git:
#        repo: 'https://github.com/vim/vim.git'
#        depth: 1
#        dest: /tmp/vim
#        version: master
#-
#    name: configure, build and install vim
#    command: "{{ item }}"
#    with_items:
#        - "./configure --with-features=huge \
#        --enable-multibyte \
#        --enable-rubyinterp=yes \
#        --enable-python3interp=yes \
#        --with-python3-config-dir=\
#        /usr/lib/python3.4/config-3.4m-x86_64-linux-gnu \
#        --enable-perlinterp=yes \
#        --enable-luainterp=yes \
#        --enable-gui=gtk2 \
#        --enable-cscope \
#        --prefix=/usr/local"
#        - "make"
#        - "make install"
#    args:
#        chdir: /tmp/vim
#        creates: /usr/local/bin/vim
-
    name: set up vim defaults
    alternatives:
        name: "{{ item.name }}"
        path: "{{ item.path }}"
    with_items:
      #TODO: how do we find out where vim is? is there a way to detect vim and then plug it into the path variable?
        - {name: "editor", path: "/usr/bin/vim"}
        - {name: "vi", path: "/usr/bin/vim"}
    become: yes
