---
# assumes yadm has already been run. my dotfiles assume directory
# structure seend below requires python
-
    name: Grab vundle for vim
    git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim
        version: master
-
    name: Pull in all vim plugins
    command: vim +PluginInstall +qall
    args:
        creates: ~/.vim/bundle/ack.vim
-
    name: Install cmake (needed by youcompleteme) and last pass
    # (cmake3 for old ubuntus. switch to just cmake for new ubuntus)
    apt:
        name: cmake
        state: present
-
    name: Install youcomplete me with clang completion
    command: ~/.pyenv/versions/3.7.3/bin/python ./install.py --clang-completer
    args:
        chdir: ~/.vim/bundle/YouCompleteMe
        creates: ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so
-
    name: make undo, backup and swap directories for vim
    file:
        path: "{{ item }}"
        state: directory
    with_items:
        - "~/.vim/undo"
        - "~/.vim/backup"
        - "~/.vim/swap"
