---
# assumes yadm has already been run. my dotfiles assume directory
# structure seend below requires python
-
    name: Grab vundle for vim
    git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: "{{ ansible_facts['user_dir'] }}/.vim/bundle/Vundle.vim"
        version: master
-
    name: Pull in all vim plugins
    command: vim +PluginInstall +qall
    args:
        creates: "{{ ansible_facts['user_dir'] }}/.vim/bundle/ack.vim"
-
    name: Install cmake (needed by youcompleteme) and last pass
    apt:
        name: cmake
        state: present
    become: yes
-
    name: Install youcomplete me with clang completion
    command: "{{ ansible_facts['user_dir'] }}/.pyenv/versions/3.7.3/bin/python ./install.py --clang-completer"
    args:
        chdir: "{{ ansible_facts['user_dir'] }}/.vim/bundle/YouCompleteMe"
        creates: "{{ ansible_facts['user_dir'] }}/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so"
-
    name: make undo, backup and swap directories for vim
    file:
        path: "{{ item }}"
        state: directory
    with_items:
        - "{{ ansible_facts['user_dir'] }}/.vim/undo"
        - "{{ ansible_facts['user_dir'] }}/.vim/backup"
        - "{{ ansible_facts['user_dir'] }}/.vim/swap"
