---
-
    name: install YADM without messing with the apt repositories
    get_url:
        url: https://github.com/TheLocehiliosan/yadm/raw/master/yadm
        dest: /usr/local/bin/yadm
        mode: a+x
    become: true
-
    name: figure out whether my dotfiles are already installed
    stat: path=/home/vagrant/.yadm/repo.git
    register: yadm_exists
-
    name: YADM clone my repo
    command: yadm clone https://github.com/austinwiltshire/yadm.git
    creates: /home/vagrant/.yadm/repo.git
    when: yadm_exists.stat.exists == False
-
    name: Switch YADM to using keys
    command: yadm remote set-url origin git@github.com:austinwiltshire/yadm.git
