---
-
    name: install YADM without messing with the apt repositories
    get_url:
        url: https://github.com/TheLocehiliosan/yadm/raw/master/yadm
        dest: "{{ ansible_facts['user_dir'] }}/.local/bin/yadm"
        mode: a+x
-
    name: Clone YADM from https, but convert to ssh after
    command: "{{ ansible_facts['user_dir'] }}/.local/bin/yadm {{ item }}"
    args:
        creates: "{{ ansible_facts['user_dir'] }}/.config/yadm/repo.git/config"
    with_items:
        - "clone https://github.com/austinwiltshire/yadm.git"
        - "remote set-url origin git@github.com:austinwiltshire/yadm.git"
