---
-
    name: install zsh
    apt:
        name: zsh
        state: present
    become: yes
- 
    name: install oh my zsh
    include_role: 
      name: gantsign.oh-my-zsh
    vars:
      users:
        - username: "{{ ansible_facts['user_id'] }}"
    #TODO: this may need to be moved up as its used by a lot of things
    #    name: Creates tmp directory
    #file:
    #    path: "{{ ansible_facts['user_dir'] }}/.local/tmp"
    #    state: directory
-
    name: clone fzf
    git:
        repo: 'https://github.com/junegunn/fzf.git'
        depth: 1
        dest: "{{ ansible_facts['user_dir'] }}/.fzf"
-
    name: install fzf
    command: "{{ ansible_facts['user_dir'] }}/.fzf/install"
-
#TODO: needs to have permissions changed compaudit | xargs chmod g-w,o-w
    name: clone autosuggestions plugin
    git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
        dest: '{{ ansible_facts['user_dir'] }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
-
#TODO: needs to have permissions changed compaudit | xargs chmod g-w,o-w
    name: clone syntax highlighting plugin
    git:
        repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
        dest: '{{ ansible_facts['user_dir'] }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
