---
-
    name: install zsh
    apt:
        name: zsh
        state: present
    become: yes
    #-
    #name: set zsh as default shell to user
    #user:
    #    name: austinwiltshire
    #    shell: /bin/zsh
    #become: yes/
- 
    #TODO: this may need to be moved up as its used by a lot of things
    name: Creates tmp directory
    file:
        path: "{{ ansible_facts['user_dir'] }}/.local/tmp"
        state: directory
-   
    name: Download zsh installer
    get_url: url=https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh dest={{ ansible_facts['user_dir'] }}/.local/tmp/zsh-installer.sh
-   
    name: Execute the zsh-installer.sh
    command: "sh {{ ansible_facts['user_dir'] }}/.local/tmp/zsh-installer.sh"
    args:
        creates: "{{ ansible_facts['user_dir'] }}/.oh-my-zsh/README.md"
    become: yes
    #-
#    debug: var=ansible_facts
#    become: yes
#-
#    name: install oh-my-zsh
#    git:
#        repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
#        depth: 1
#        dest: ~/.oh-my-zsh
#        version: master
