---
-
    name: install zsh
    apt:
        name: zsh
        state: present
    become: yes
- 
    name: install oh my zsh
    include_role: 
      name: gantsign.oh-my-zsh
    vars:
      users:
        - username: "{{ ansible_facts['user_id'] }}"
    #TODO: this may need to be moved up as its used by a lot of things
    #    name: Creates tmp directory
    #file:
    #    path: "{{ ansible_facts['user_dir'] }}/.local/tmp"
    #    state: directory
